"use strict";
const T={
en:{demos:"Demos",principles:"Principles",eyebrow:"INTERACTIVE PORTFOLIO / 001",hero1:"Evidence first.",hero2:"Decisions stay human.",heroText:"Three small, interactive demonstrations of how a PV system can make process state, data quality, and source evidence visible.",explore:"Explore the demos",synthetic:"100% synthetic records and documents",studies:"SELECTED SYSTEM STUDIES",logic:"Explore the logic.",intro:"Each demo runs entirely in your browser. Try the controls to see what changes and why.",workflow:"PV workflow",quality:"Data quality",retrieval:"Source retrieval",fictional:"FICTIONAL SPECIMEN",wTitle:"A case is a sequence of accountable decisions.",wText:"Select a stage to inspect its required evidence and review gate. This example never advances a real case.",selected:"SELECTED STAGE",evidence:"EVIDENCE NEEDED",gate:"REVIEW GATE",human:"Human review remains required",qTitle:"Show the rule behind every flag.",qText:"Run deterministic checks on five synthetic rows. Add one issue to see the report update.",run:"Run checks",add:"Add missing date",restore:"Restore date",id:"Record ID",event:"Event date",received:"Received date",source:"Source",result:"Check result",rules:"RULES IN THIS DEMO",rule1:"Required dates must be present.",rule2:"A received date cannot precede an event date.",rule3:"Record IDs must be unique.",rTitle:"Find a passage. Keep its context.",rText:"Search an invented document set. Results retain their document title and section locator so a person can verify the source.",searchLabel:"Search illustrative sources",search:"Search ↗",notice:"All passages are invented for this demonstration. They are not laws, guidance, or compliance advice.",design:"DESIGN PRINCIPLES",trace:"Built for traceability.",p1:"Visible state",p1Text:"Every stage shows the evidence required and the person responsible for review.",p2:"Explainable checks",p2Text:"A quality flag points to a named rule and the affected synthetic row.",p3:"Source boundaries",p3Text:"Retrieved text keeps its locator and stays separate from a human conclusion.",boundary:"Portfolio demonstration only. No company code, patient records, licensed terminology, network data transfer, or real regulatory claims are included.",pass:"PASS",pending:"NOT RUN",missing:"Missing event date",early:"Received before event",duplicate:"Duplicate ID",searchHint:"Try: review, timeline, source",empty:"No matching passage. Try a suggested term.",badge:"ILLUSTRATIVE SOURCE · NOT LEGAL TEXT"},
zh:{demos:"交互演示",principles:"设计原则",eyebrow:"交互作品集 / 001",hero1:"证据先行。",hero2:"判断由人负责。",heroText:"三个可交互的小演示，展示 PV 系统如何清楚呈现流程状态、数据质量和来源依据。",explore:"查看演示",synthetic:"全部为合成记录及虚构文档",studies:"系统设计演示",logic:"看得见的处理逻辑。",intro:"所有交互都在浏览器本地运行。试试各项操作，看看结果如何变化。",workflow:"PV 工作流",quality:"数据质控",retrieval:"法规检索示意",fictional:"虚构示例",wTitle:"每一步都需要明确的证据和责任。",wText:"选择一个阶段，查看所需证据和人工审核关口。此处不会推进任何真实个例。",selected:"当前阶段",evidence:"所需证据",gate:"审核关口",human:"始终需要人工审核",qTitle:"每个质控标记都有具体规则。",qText:"对五条合成数据运行确定性检查。加入一个问题，观察结果变化。",run:"运行检查",add:"制造日期缺失",restore:"恢复日期",id:"记录编号",event:"事件日期",received:"接收日期",source:"来源",result:"检查结果",rules:"本演示的规则",rule1:"必填日期不能为空。",rule2:"接收日期不能早于事件日期。",rule3:"记录编号不能重复。",rTitle:"找到段落，也保留上下文。",rText:"检索虚构文档。每条结果保留文档名称和章节定位，方便人工核对。",searchLabel:"检索示例材料",search:"检索 ↗",notice:"所有段落均为演示而虚构，不属于法规、指南或合规建议。",design:"设计原则",trace:"让依据可以追溯。",p1:"状态清楚",p1Text:"每个阶段展示所需证据及人工审核责任。",p2:"规则可解释",p2Text:"每项质控标记均对应具体规则和受影响的示例行。",p3:"来源有边界",p3Text:"检索内容保留定位信息，并与人工结论分开。",boundary:"仅供作品集演示。不包含公司代码、患者记录、许可术语、网络数据传输或真实法规主张。",pass:"通过",pending:"未运行",missing:"事件日期缺失",early:"接收早于事件",duplicate:"编号重复",searchHint:"试试：审核、时限、来源",empty:"没有匹配段落，请尝试建议关键词。",badge:"虚构材料 · 非法规原文"}};
const stages=[
{en:["Intake","Capture the initial report without assuming the facts are complete.","Receipt timestamp and source reference","Confirm report provenance"],zh:["接收","记录初始报告，不预设事实完整。","接收时间及来源记录","核对报告来源"]},
{en:["Triage","Check completeness and route uncertain fields for follow-up.","Completeness checklist","Reviewer confirms next action"],zh:["分流","核查完整性，将不确定字段标记为待补充。","完整性检查单","审核人确认后续动作"]},
{en:["Assessment","Compare available information with the documented criteria.","Linked source records and rationale","Qualified assessment review"],zh:["评估","依据已记录的标准核对现有信息。","关联来源及判断依据","由具备资格的人员复核"]},
{en:["Close-out","Record the decision, remaining gaps, and audit trail.","Decision record and change history","Final human sign-off"],zh:["结项","记录结论、未解决事项和变更轨迹。","决定记录及变更历史","人工最终签核"]}];
const rows=[["SYN-001","2026-01-04","2026-01-06","Demo form"],["SYN-002","2026-01-08","2026-01-09","Demo inbox"],["SYN-003","2026-01-12","2026-01-11","Demo form"],["SYN-004","2026-01-15","2026-01-16","Demo inbox"],["SYN-004","2026-01-19","2026-01-20","Demo form"]];
const sources=[
{id:"ILL-01",loc:"§ 2.1",en:["Illustrative Review Manual","A reviewer records the source, timeline, and reason for each decision before a sample record is closed."],zh:["虚构审核手册","示例记录结项前，审核人记录来源、时限和每项决定的理由。"]},
{id:"ILL-02",loc:"§ 3.4",en:["Illustrative Source Guide","When a source cannot be verified, the uncertainty is shown alongside the retrieved passage and sent for human review."],zh:["虚构来源指南","无法核实来源时，应在检索段落旁标明不确定性，并提交人工审核。"]},
{id:"ILL-03",loc:"§ 5.2",en:["Illustrative Workflow Note","The sample timeline tracks receipt, review, and sign-off separately so an overdue step can be identified."],zh:["虚构流程说明","示例时限分别记录接收、审核和签核，以便识别超期步骤。"]}];
let lang="en",stage=0,checked=false,injected=false,query="";
const $=s=>document.querySelector(s);
function node(tag,cls,value){const el=document.createElement(tag);if(cls)el.className=cls;if(value!==undefined)el.textContent=value;return el}
function renderStage(){const list=$("#stages");list.replaceChildren();stages.forEach((s,i)=>{const b=node("button","",undefined);b.type="button";b.setAttribute("aria-pressed",String(stage===i));b.append(node("span","",String(i+1).padStart(2,"0")),document.createTextNode(s[lang][0]));b.addEventListener("click",()=>{stage=i;renderStage()});list.append(b)});const s=stages[stage][lang];$("#stage-count").textContent=`${String(stage+1).padStart(2,"0")} / 04`;["name","description","evidence","gate"].forEach((field,i)=>{$(`#stage-${field}`).textContent=s[i]})}
function renderQuality(){const body=$("#quality-rows");body.replaceChildren();let passed=0;rows.forEach((r,i)=>{const cells=[r[0],injected&&i===0?"":r[1],r[2],r[3]];const flags=[];if(!cells[1]||!cells[2])flags.push(T[lang].missing);if(cells[1]&&cells[2]<cells[1])flags.push(T[lang].early);if(rows.filter(x=>x[0]===r[0]).length>1)flags.push(T[lang].duplicate);if(!flags.length)passed++;const tr=node("tr");cells.forEach(value=>tr.append(node("td","",value||"—")));tr.append(node("td",checked?(flags.length?"flag":"pass"):"pending",checked?(flags.length?flags.join(" · "):T[lang].pass):T[lang].pending));body.append(tr)});$("#quality-summary").textContent=checked?(lang==="en"?`${passed} of ${rows.length} rows pass · inspect flags before use`:`${rows.length} 行中 ${passed} 行通过 · 使用前请检查标记`):""}
function renderSearch(){const term=query.trim().toLocaleLowerCase();const found=term?sources.filter(s=>[s.id,s.loc,...s.en,...s.zh].join(" ").toLocaleLowerCase().includes(term)):sources;$("#search-count").textContent=lang==="en"?`${found.length} illustrative passage${found.length===1?"":"s"}`:`找到 ${found.length} 条虚构段落`;const box=$("#search-results");box.replaceChildren();if(!found.length){box.append(node("p","empty",T[lang].empty));return}found.forEach(s=>{const card=node("article","result-card");card.append(node("code","",`${s.id} / ${s.loc}`),node("h4","",s[lang][0]),node("p","",s[lang][1]),node("div","badge",T[lang].badge));box.append(card)})}
function setLanguage(next){lang=next;document.documentElement.lang=lang;$("#language").textContent=lang==="en"?"中文":"EN";$("#language").setAttribute("aria-label",lang==="en"?"Switch to Chinese":"切换至英文");document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=T[lang][el.dataset.i18n]);$("#inject").textContent=T[lang][injected?"restore":"add"];$("#query").placeholder=T[lang].searchHint;renderStage();renderQuality();renderSearch()}
function setTab(name){document.querySelectorAll(".tabs button").forEach(b=>{const active=b.dataset.tab===name;b.setAttribute("aria-selected",String(active));b.tabIndex=active?0:-1});document.querySelectorAll(".panel").forEach(p=>p.hidden=p.id!==`panel-${name}`)}
document.querySelectorAll(".tabs button").forEach((b,i,all)=>{b.addEventListener("click",()=>setTab(b.dataset.tab));b.addEventListener("keydown",event=>{if(!["ArrowLeft","ArrowRight"].includes(event.key))return;event.preventDefault();const n=(i+(event.key==="ArrowRight"?1:-1)+all.length)%all.length;setTab(all[n].dataset.tab);all[n].focus()})});
$("#language").addEventListener("click",()=>setLanguage(lang==="en"?"zh":"en"));
$("#run").addEventListener("click",()=>{checked=true;renderQuality()});
$("#inject").addEventListener("click",()=>{injected=!injected;$("#inject").textContent=T[lang][injected?"restore":"add"];renderQuality()});
$("#search-form").addEventListener("submit",event=>{event.preventDefault();query=$("#query").value;renderSearch()});
document.querySelectorAll(".chips button").forEach(b=>b.addEventListener("click",()=>{query=b.dataset.query;$("#query").value=query;renderSearch()}));
$("#year").textContent=new Date().getFullYear();setLanguage("en");
